version: "3.8"
services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: alex-test-php-fpm
    restart: unless-stopped
    environment:
      - PGID=${PHP_FPM_PGID}
      - PUID=${PHP_FPM_PUID}
      - USER=${PHP_FPM_USER}
    volumes:
      - ./storage/logs/:/var/log/php/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/alex-test.local/
    working_dir: /var/www/alex-test.local/
    networks:
      - alex-test-net

  nginx:
    build: ./docker/nginx
    container_name: alex-test-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/alex-test.local/
      - ./storage/logs/:/var/log/nginx_log/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - alex-test-net

  mysql:
    build: ./docker/mysql
    container_name: alex-test-mysql
    restart: unless-stopped
    volumes:
      - ./storage/logs/:/var/log/mysql/
      - ./docker/mysql/data/:/var/lib/mysql/
      - ./docker/mysql/conf.cnf:/etc/mysql/conf.d/conf.cnf
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - alex-test-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: alex-test-phpmyadmin
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    networks:
      - alex-test-net

networks:
  alex-test-net:
    name: alex-test-net
    driver: bridge
